apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      serviceAccount: tolkein
      containers:
      - name: telegraf
        image: my_telegraf
        imagePullPolicy: Never
        env:
          - name: INFLUXDB_USER
            value: gandalf            
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: telegraf-secret
                key: influxdb_userpass
---

apiVersion: v1
kind: ServiceAccount
metadata:
    name: tolkein
    namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telegraf-role
rules: 
- apiGroups: ["", "extensions", "apps"]
  resources: ["daemonsets", "deployments", "endpoints", "ingresses", "nodes", "nodes/proxy","persistentvolumes", "persistentvolumeclaims", "pods", "services", "statefulsets"]
  verbs: ["get", "watch", "list"]
---
  
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: telegraf-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telegraf-role
subjects:
- kind: ServiceAccount
  name: tolkein
  namespace: default