# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Dockerfile                                         :+:    :+:             #
#                                                      +:+                     #
#    By: evelina <evelina@student.codam.nl>           +#+                      #
#                                                    +#+                       #
#    Created: 2020/04/20 15:27:07 by evelina       #+#    #+#                  #
#    Updated: 2020/05/12 14:55:54 by evelina       ########   odam.nl          #
#                                                                              #
# **************************************************************************** #


FROM debian:buster

RUN apt-get update -y && apt-get upgrade -y

